style = "yas"
indent = 4
margin = 92
# Syntax transformations.
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
pipe_to_function_call = true
short_to_long_function_def = true
always_use_return = true
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
format_docstrings = true
conditional_to_if = true
normalize_line_endings = "auto"
trailing_comma = true
trailing_zero = true
join_lines_based_on_source = false
indent_submodule = true
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
for_in_replacement = "âˆˆ"
short_circuit_to_if = true
overwrite = true
verbose = true
format_markdown = true
# Alignment
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
align_matrix = true
